spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot?userSSL=false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot?userSSL=false
    username: taylor
    password: pass

  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration
    enabled: true

  main:
    allow-bean-definition-overriding: true

  data:
    neo4j:
      uri: bolt://localhost:7687
      authentication:
        username: neo4j
        password: 12345678

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    hibernate:
      ddl-auto: validate
      generate-ddl: false

# 운영용
#      ddl-auto: validate
#      generate-ddl: false

# h2 setting
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true